version: "3.9"

networks:
  mcp:

services:
  mcp_server_name:
    build:
      context: ./mcp_servers/servers/server_name/
      dockerfile: Dockerfile
    container_name: mcp_server_name
    hostname: mcp_server_name
    networks:
      - mcp
    ports:
      - "5050:5050"
    env_file:
      - .env

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent
    hostname: agent
    networks:
      - mcp
    ports:
      - "5051:5051"
    depends_on:
      - mcp_server_name
    environment:
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - MCP_SERVER_NAME_NAME=${MCP_SERVER_NAME_NAME}
      - MCP_SERVER_NAME_PORT=${MCP_SERVER_NAME_PORT}
    env_file:
      - .env
    command: bash -c "python3 main.py || tail -f /dev/null"
