version: "3.9"

networks:
  marea-network:
    driver: bridge

services:
  # Supabase MCP Server
  supabase-mcp:
    build:
      context: ./mcp_integration/servers/supabase
    container_name: supabase-mcp-server
    environment:
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]

  # Finance MCP Server
  finance-mcp:
    build:
      context: ./mcp_integration/servers/finance
    container_name: finance-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]

  # Main app (marea == agent)
  marea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marea-main
    depends_on:
      - supabase-mcp
      - finance-mcp
    volumes:
      # Keep this only if you need to exec into other containers from here
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "8000:8000"
      - "5051:5051"
    restart: unless-stopped
    command: python app.py
    networks: [marea-network]