version: '3.8'

services:
  # Supabase MCP Server
  mcp-server:
    image: node:18-alpine
    container_name: civic-assistant-mcp
    command: >
      sh -c "
        npm install -g @supabase/mcp-server-supabase &&
        npx @supabase/mcp-server-supabase 
        --project-ref ${SUPABASE_PROJECT_REF} 
        --read-only
      "
    environment:
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
    ports:
      - "3001:3000"  # MCP server port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
