services:
  supabase:
    image: node:18-alpine
    command: >
      sh -c "
        npm install -g @supabase/mcp-server-supabase &&
        npx @supabase/mcp-server-supabase --project-ref ${SUPABASE_PROJECT_REF} --read-only
      "
    environment:
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
    ports:
      - "3001:3001"
