version: "3.9"

networks:
  marea-network:
    driver: bridge

services:
  # Supabase MCP Server
  supabase-mcp:
    build:
      context: ./mcp_kit/servers/supabase
    container_name: supabase-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]

  # Finance MCP Server
  finance-mcp:
    build:
      context: ./mcp_kit/servers/finance
    container_name: finance-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]

  # Location MCP Server
  location-mcp:
    build:
      context: ./mcp_kit/servers/location
    container_name: location-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]

  # Main app (marea == agent)
  marea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marea-main
    depends_on:
      - supabase-mcp
      - finance-mcp
      - location-mcp
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Keep this only if you need to exec into other containers from here
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "8000:8000"
    command: python gradio_app.py
    networks: [marea-network]
    user: "0:0"  # Run as root to access docker socket