---
name: MCP Tests

on:
  push:
    branches:
      - "main"

jobs:
  mcp_tests:
    runs-on: "ubuntu-latest"
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
      LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
      LANGSMITH_TRACING: ${{ secrets.LANGSMITH_TRACING }}
      LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      READONLY_DATABASE_URL: ${{ secrets.READONLY_DATABASE_URL }}
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install Poetry"
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
          cache: "poetry"
          cache-dependency-path: "./poetry.lock"

      - name: "Install dependencies"
        run: "poetry install --no-root"

      - name: "MCP Tests"
        run: "poetry run python -m pytest tests"
